app/urls.py
from django.conf.urls import url
from . import views


app_name = 'app'
urlpatterns = [
    url('^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^quiz/$', views.quiz, name='quiz'),
    url(r'^actualquiz/(\d+)$', views.actualquiz, name='actualquiz'),
    url(r'^user_profile/(\d+)$',
        views.user_profile, name='user_profile'),
    url(r'^add_game/$', views.add_game, name='add_game'),
    url(r'^user_profiles/$', views.get_user_profiles, name='user_profiles')
]

quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, documnet_root=settings.STATIC_ROOT)

app/templates/app/add_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
@import url(http://weloveiconfonts.com/api/?family=entypo);

/* entypo */
[class*="entypo-"]:before {
  font-family: 'entypo', sans-serif;
}

body {
    height:100%;
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
    font-size: 1em;
    font-weight: 300;
    line-height: 1.5;
    letter-spacing: 0.05em;
    background-image: linear-gradient(135deg, rgba(35, 28, 24, 0.8) 0%,rgba(153, 135, 123, 0.8) 100%);
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    background-size: cover;

}

* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

.avatar {
  background-image: url("http://www.lovemarks.com/wp-content/uploads/profile-avatars/default-avatar.png");
  background-size: cover;
  border-radius: 100%;
  margin: 4rem auto 2rem auto;
  width: 10rem;
  height: 10rem;
  box-shadow: 0 0 0 8px rgba(255,255,255,0.2);
  transition: all 0.5s ease-in-out;
}

.avatar:hover {
  box-shadow: 0 0 0 12px rgba(255,255,255,0.6);
}

h1 {
  text-align:center;
  font-size:24px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0;
}

h3 {
  text-align:center;
  font-size:16px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0.5em 0 1em 0;
}

p {
  text-align:center;
  font-size:12px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
}

.container {
	left: 50%;
	margin:6em 0 0 -108px;
	position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 13.5em;
}

.social li {
  border-radius:10px;
	display: block;
	height: 4em;
	line-height: 4em;
	margin: -2.2em;
	position: absolute;
	transition: all 0.5s ease-in-out;
	transform: rotate(45deg);
	text-align: center;
	width: 4em;
  box-shadow: 0 0 0 2px rgba(255,255,255,0.4);
}

.social a {
	color: #ffffff;
  text-decoration:none;
	display: block;
	height: 4em;
	line-height: 4em;
	text-align: center;
	transform: rotate(-45deg);
	width: 4em;
}

@media only screen
and (max-width : 320px) {

.container {
left: 50%;
margin: 5em 0 0 -64px;
position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 10em;
}

.social li {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

.social a {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

}

.facebook {
  background:rgba(255,255,255,0.1);
	left: 0;
	top: 0%;
}

.facebook:hover{
  background:#155b9d;
  box-shadow: 0 0 0 2px #155b9d;
}

.twitter {
  background:rgba(255,255,255,0.1);
	bottom: 0;
	left: 25%;
}

.twitter:hover{
  background:#4099FF;
  box-shadow: 0 0 0 2px #4099FF;
}


.sociali {
  background:rgba(255,255,255,0.1);
	left: 50%;
	top: 0;
}

.sociali:hover{
  background:#f34141;
  box-shadow: 0 0 0 2px #f34141;
}

.codepen {
  background:rgba(255,255,255,0.1);
	left: 75%;
	bottom: 0;
}

.codepen:hover{
  background:#333333;
  box-shadow: 0 0 0 2px #333333;
}


.mail {
  background:rgba(255,255,255,0.1);
  left: 100%;
	top: 0;
}

.mail:hover{
  background:#1abc9c;
  box-shadow: 0 0 0 2px #1abc9c;
}


h1, h2, h4{
    text-align: center;
}



.search-container{
    position: absolute;
    top: 4%;
    left: 50%;
    transform: translate(-50%, -50%);
}

.search-input{
    padding: 10px 20px;
    border: none;
    border-radius: 20px;
    font-size: 16px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    transition: width 0.3s ease-in-out;
}
.search-input:focus{
    width: 300px;
}

.search-button{
    position: absolute;
    top: 0;
    right: 0;
    height: 100%;
    background-color: transparent;
    border: none;
    outline: none;
    cursor: pointer;
}

.search-button i{
    font-size: 18px;
    color: #888;
    transition: color 0.3s ease-in-out;
}

.search-button:hover{
    color: #333;
}

.adding_word{
    text-align: center;
}

</style>

</head>
<body>
    <h1>Dodaj słowo</h1>
    <br>
    <form method="post" style="text-align: center">
        {%  csrf_token %}
        <label for="question">Słowo:</label>
        {{ form.question }}
        <br>
        <br>
        <label for="answer">Synonim:</label>
        {{ form.answer }}
        <br>
        <br>
        <label for="description1">Opis:</label>
        {{ form.description1 }}
        <br>
        <br>
        <button type="submit">Dodaj</button>
    </form>

<div class="container">
   <ul class="social">
     <li class="sociali"><a href="{% url 'app:search' %}">Szukaj</a></li>
   </ul>

 </div>
</body>
</html>

app/templates/app/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Quiz Trigger - Login Page</title>



      <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>

<body>

  <div class="wrapper">
	<div class="container">
		<h1>Witaj!</h1>

		<form class="form" method="post" action="{% url 'app:login' %}">
      {% csrf_token %}
			<input type="text" placeholder="Login" name="username" required>
			<input type="password" placeholder="Hasło" name="password"required>
			<button type="submit">Zaloguj</button>
		</form>
        <br />
        <h2>Jeżeli jesteś tu pierwszy raz</h2>
        <form class="form" action="http://127.0.0.1:8000/register/">
            <button type=" submit" value="Przejdz do rejestracji">Zarejestruj sie</button>
        </form>
	</div>
  {% if error %}
  {{ error }}
  {% endif %}
	<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>



    <script  src="{% static 'js/index.js' %}"></script>




</body>

</html>

app/templates/app/quiz.html
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
@import url(http://weloveiconfonts.com/api/?family=entypo);

/* entypo */
[class*="entypo-"]:before {
  font-family: 'entypo', sans-serif;
}

body {
  height:100%;
  font-family: 'Open Sans', Helvetica, Arial, sans-serif;
  font-size: 1em;
  font-weight: 300;
  line-height: 1.5;
  letter-spacing: 0.05em;
  background-image: linear-gradient(135deg, rgba(35, 28, 24, 0.8) 0%,rgba(153, 135, 123, 0.8) 100%);
  background-repeat: no-repeat;
  background-position: center center;
  background-attachment: fixed;
  background-size: cover;

}

* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

.avatar {
  background-image: url("http://www.lovemarks.com/wp-content/uploads/profile-avatars/default-avatar.png");
  background-size: cover;
  border-radius: 100%;
  margin: 4rem auto 2rem auto;
  width: 10rem;
  height: 10rem;
  box-shadow: 0 0 0 8px rgba(255,255,255,0.2);
  transition: all 0.5s ease-in-out;
}

.avatar:hover {
  box-shadow: 0 0 0 12px rgba(255,255,255,0.6);
}

h1 {
  text-align:center;
  font-size:24px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0;
}

form{
    text-align:center;
    padding-block: initial;
}

h3 {
  text-align:center;
  font-size:16px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0.5em 0 1em 0;
}

p {
  text-align:center;
  font-size:12px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
}

.container {
	left: 50%;
	margin:6em 0 0 -108px;
	position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 13.5em;
}

.social li {
  border-radius:10px;
	display: block;
	height: 4em;
	line-height: 4em;
	margin: -2.2em;
	position: absolute;
	transition: all 0.5s ease-in-out;
	transform: rotate(45deg);
	text-align: center;
	width: 4em;
  box-shadow: 0 0 0 2px rgba(255,255,255,0.4);
}

.social a {
	color: #ffffff;
  text-decoration:none;
	display: block;
	height: 4em;
	line-height: 4em;
	text-align: center;
	transform: rotate(-45deg);
	width: 4em;
}

@media only screen
and (max-width : 320px) {

.container {
left: 50%;
margin: 5em 0 0 -64px;
position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 10em;
}

.social li {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

.social a {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

}

.facebook {
  background:rgba(255,255,255,0.1);
	left: 0;
	top: 0%;
}

.facebook:hover{
  background:#155b9d;
  box-shadow: 0 0 0 2px #155b9d;
}

.twitter {
  background:rgba(255,255,255,0.1);
	bottom: 0;
	left: 25%;
}

.twitter:hover{
  background:#4099FF;
  box-shadow: 0 0 0 2px #4099FF;
}


.sociali {
  background:rgba(255,255,255,0.1);
	left: 50%;
	top: 0;
}

.sociali:hover{
  background:#f34141;
  box-shadow: 0 0 0 2px #f34141;
}

.codepen {
  background:rgba(255,255,255,0.1);
	left: 75%;
	bottom: 0;
}

.codepen:hover{
  background:#333333;
  box-shadow: 0 0 0 2px #333333;
}


.mail {
  background:rgba(255,255,255,0.1);
  left: 100%;
	top: 0;
}

.mail:hover{
  background:#1abc9c;
  box-shadow: 0 0 0 2px #1abc9c;
}

</style>
{%  if f == 0%}
<h1>Zagrajmy!</h1>

<form method="post" action="{% url 'app:actualquiz' quiz.id %}">
                {% csrf_token %}

                <h3>Pytanie 1 - Jaki jest synonim slowa "{{quiz.q1}}"? {{ quiz.games }}</h3>
                {% for choice in options1 %}

                    <input type="radio" name="ques1" value="{{choice}}">
                    <label for="">{{choice}}</label>
                    <br />
                {% endfor %}

                <br />

                <h3>Pytanie 2 - Jaki jest synonim slowa "{{quiz.q2}}"?</h3>
                {% for choice in options2 %}

                    <input type="radio" name="ques2" value="{{choice}}">
                    <label for="">{{choice}}</label>
                    <br />
                {% endfor %}

                <br />

                <h3>Pytanie 3 - Jaki jest synonim slowa "{{quiz.q3}}"?</h3>
                {% for choice in options3 %}

                    <input type="radio" name="ques3" value="{{choice}}">
                    <label for="">{{choice}}</label>
                    <br />
                {% endfor %}

                <br />

                <h3>Pytanie 4 - Jaki jest synonim slowa "{{quiz.q4}}"?</h3>
                {% for choice in options4 %}

                    <input type="radio" name="ques4" value="{{choice}}">
                    <label for="">{{choice}}</label>
                    <br />
                {% endfor %}

                <br />

                <button type="submit">Zatwierdz</button>
 </form>

 <div class="container">

    <ul class="social">

      <li class="facebook"><a href="{% url 'app:logout' %}">Wyloguj</a></li>
      <li class="sociali"><a href="{% url 'app:search' %}">Szukaj</a></li>
      <li class="mail"><a href="{% url 'app:user_profiles' %}">Ranking</a></li>

    </ul>

 </div>

{% endif %}

{%  if f == 1 %}


                <h3>Pytanie 1</h3>
                <h3>Synonim slowa - {{quiz.q1 }}</h3>
                <h3>Poprawna odpowiedz - {{quiz.q1.answer}}
                <h3>Twoja odpowiedz - {{quiz.q1selected}}
                <br />
                <br />
                <br />


                <h3>Pytanie 2</h3>
                <h3>Synonim slowa - {{quiz.q2}}</h3>
                <h3>Poprawna odpowiedz - {{quiz.q2.answer}}
                <h3>Twoja odpowiedz - {{quiz.q2selected}}
                <br />
                <br />
                <br />

                <h3>Pytanie 3</h3>
                <h3>Synonim slowa - {{quiz.q3 }}</h3>
                <h3>Poprawna odpowiedz - {{quiz.q3.answer}}
                <h3>Twoja odpowiedz - {{quiz.q3selected}}
                <br />
                <br />
                <br />

                <h3>Pytanie 4</h3>
                <h3>Synonim slowa - {{quiz.q4}}</h3>
                <h3>Poprawna odpowiedz - {{quiz.q4.answer}}
                <h3>Twoja odpowiedz - {{quiz.q4selected}}
                <br />
                <br />
                <br />

 <div class="container">



    <ul class="social">

      <li class="facebook"><a href="{% url 'app:logout' %}">Wyloguj</a></li>
       <li class="sociali"><a href="{% url 'app:search' %}">Szukaj</a></li>
      <li class="mail"><a href="{% url 'app:user_profiles' %}">Ranking</a></li>

    </ul>

  </div>
{% endif %}

app/templates/app/registration.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Calm breeze login screen</title>



      <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>

<body>

  <div class="wrapper">
	<div class="container">
		<h1>Cześć!</h1>

    <form method="post" action="{% url 'app:register' %}">
                    {% csrf_token %}
			<input type="text" placeholder="Login" name="username" required>
			<input type="password" placeholder="Hasło" name="password"required>
      <input type="email" placeholder="Email" name="email" required>
			<input type="text" placeholder="BIO" name="bio" required>
      <input type="text" placeholder="Imię" name="first_name" required>
			<input type="text" placeholder="Nazwisko" name="last_name" required>
      <input type="text" placeholder="Numer kontaktowy" name="mobileNo" required>
      <select name="gender">
          <option value="Mężczyzna">Mężczyzna</option>
          <option value="Kobieta">Kobieta</option>
      </select>
      <br>
      <br>
			<button type="submit">Zarejestruj</button>
		</form>
	</div>
  {% if error %}
  {{ error }}
  {% endif %}
	<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>



    <script  src="{% static 'js/index.js' %}"></script>




</body>

</html>

app/templates/app/search.html
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
@import url(http://weloveiconfonts.com/api/?family=entypo);

/* entypo */
[class*="entypo-"]:before {
  font-family: 'entypo', sans-serif;
}

body {
    height:100%;
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
    font-size: 1em;
    font-weight: 300;
    line-height: 1.5;
    letter-spacing: 0.05em;
    background-image: linear-gradient(135deg, rgba(35, 28, 24, 0.8) 0%,rgba(153, 135, 123, 0.8) 100%);
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    background-size: cover;

}

* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

.avatar {
  background-image: url("http://www.lovemarks.com/wp-content/uploads/profile-avatars/default-avatar.png");
  background-size: cover;
  border-radius: 100%;
  margin: 4rem auto 2rem auto;
  width: 10rem;
  height: 10rem;
  box-shadow: 0 0 0 8px rgba(255,255,255,0.2);
  transition: all 0.5s ease-in-out;
}

.avatar:hover {
  box-shadow: 0 0 0 12px rgba(255,255,255,0.6);
}

h1 {
  text-align:center;
  font-size:24px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0;
}

h3 {
  text-align:center;
  font-size:16px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0.5em 0 1em 0;
}

p {
  text-align:center;
  font-size:12px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
}

.container {
	left: 50%;
	margin:6em 0 0 -108px;
	position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 13.5em;
}

.social li {
  border-radius:10px;
	display: block;
	height: 4em;
	line-height: 4em;
	margin: -2.2em;
	position: absolute;
	transition: all 0.5s ease-in-out;
	transform: rotate(45deg);
	text-align: center;
	width: 4em;
  box-shadow: 0 0 0 2px rgba(255,255,255,0.4);
}

.social a {
	color: #ffffff;
  text-decoration:none;
	display: block;
	height: 4em;
	line-height: 4em;
	text-align: center;
	transform: rotate(-45deg);
	width: 4em;
}

@media only screen
and (max-width : 320px) {

.container {
left: 50%;
margin: 5em 0 0 -64px;
position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 10em;
}

.social li {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

.social a {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

}

.facebook {
  background:rgba(255,255,255,0.1);
	left: 0;
	top: 0%;
}

.facebook:hover{
  background:#155b9d;
  box-shadow: 0 0 0 2px #155b9d;
}

.twitter {
  background:rgba(255,255,255,0.1);
	bottom: 0;
	left: 25%;
}

.twitter:hover{
  background:#4099FF;
  box-shadow: 0 0 0 2px #4099FF;
}


.sociali {
  background:rgba(255,255,255,0.1);
	left: 50%;
	top: 0;
}

.sociali:hover{
  background:#f34141;
  box-shadow: 0 0 0 2px #f34141;
}

.codepen {
  background:rgba(255,255,255,0.1);
	left: 75%;
	bottom: 0;
}

.codepen:hover{
  background:#333333;
  box-shadow: 0 0 0 2px #333333;
}


.mail {
  background:rgba(255,255,255,0.1);
  left: 100%;
	top: 0;
}

.mail:hover{
  background:#1abc9c;
  box-shadow: 0 0 0 2px #1abc9c;
}


h1, h2, h4{
    text-align: center;
}



.search-container{
    position: absolute;
    top: 4%;
    left: 50%;
    transform: translate(-50%, -50%);
}

.search-input{
    padding: 10px 20px;
    border: none;
    border-radius: 20px;
    font-size: 16px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    transition: width 0.3s ease-in-out;
}
.search-input:focus{
    width: 300px;
}

.search-button{
    position: absolute;
    top: 0;
    right: 0;
    height: 100%;
    background-color: transparent;
    border: none;
    outline: none;
    cursor: pointer;
}

.search-button i{
    font-size: 18px;
    color: #888;
    transition: color 0.3s ease-in-out;
}

.search-button:hover{
    color: #333;
}
</style>

<form>
<br /><br />
<div class="search-container">
    <input type="text" placeholder="Wyszukaj..." class="search-input" name="search">
    <button type="submit" class="search-button">
        <i class="fas fa-search"></i>
    </button>
</div>
</form>
<hr style="height: 5px; background: black;">
{% if questions %}
  {% for g in questions %}
      <h1>{{g.question}}</h1><h2>{{g.answer}}</h2><h4>{{ g.description1 }}</h4>
    <hr style="color: white; width: 50%">
      <br />
  {% endfor %}
{% endif %}
{% if error %}
  <h1>NO MATCHES FOUND</h1>
{% endif %}


<div class="container">



   <ul class="social">

     <li class="facebook"><a href="{% url 'app:logout' %}">Wyloguj</a></li>
      <li class="sociali"><a href="{% url 'app:quiz' %}">Quiz</a></li>
     <li class="mail"><a href="{% url 'app:user_profile' prof.id %}">Profil</a></li>

   </ul>

 </div>

app/templates/app/user_profile.html
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
@import url(http://weloveiconfonts.com/api/?family=entypo);

/* entypo */
[class*="entypo-"]:before {
  font-family: 'entypo', sans-serif;
}

body {
  height:100%;
  font-family: 'Open Sans', Helvetica, Arial, sans-serif;
  font-size: 1em;
  font-weight: 300;
  line-height: 1.5;
  letter-spacing: 0.05em;
  background-image: linear-gradient(135deg, rgba(35, 28, 24, 0.8) 0%,rgba(153, 135, 123, 0.8) 100%);
  background-repeat: no-repeat;
  background-position: center center;
  background-attachment: fixed;
  background-size: cover;

}

* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

.avatar {
  background-image: url("http://www.lovemarks.com/wp-content/uploads/profile-avatars/default-avatar.png");
  background-size: cover;
  border-radius: 100%;
  margin: 4rem auto 2rem auto;
  width: 10rem;
  height: 10rem;
  box-shadow: 0 0 0 8px rgba(255,255,255,0.2);
  transition: all 0.5s ease-in-out;
}

.avatar:hover {
  box-shadow: 0 0 0 12px rgba(255,255,255,0.6);
}

h1 {
  text-align:center;
  font-size:24px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0;
}

h3 {
  text-align:center;
  font-size:16px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
  margin: 0.5em 0 1em 0;
}

p {
  text-align:center;
  font-size:12px;
  font-weight:300;
  color:#ffffff;
  text-shadow: 1px 1px 2px #444444;
}

.container {
	left: 50%;
	margin:6em 0 0 -108px;
	position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 13.5em;
}

.social li {
  border-radius:10px;
	display: block;
	height: 4em;
	line-height: 4em;
	margin: -2.2em;
	position: absolute;
	transition: all 0.5s ease-in-out;
	transform: rotate(45deg);
	text-align: center;
	width: 4em;
  box-shadow: 0 0 0 2px rgba(255,255,255,0.4);
}

.social a {
	color: #ffffff;
  text-decoration:none;
	display: block;
	height: 4em;
	line-height: 4em;
	text-align: center;
	transform: rotate(-45deg);
	width: 4em;
}

@media only screen
and (max-width : 320px) {

.container {
left: 50%;
margin: 5em 0 0 -64px;
position: absolute;
}

.social {
	position: relative;
	height: 3em;
	width: 10em;
}

.social li {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

.social a {
	height: 3em;
	line-height: 3em;
	width: 3em;
}

}

.facebook {
  background:rgba(255,255,255,0.1);
	left: 0;
	top: 0%;
}

.facebook:hover{
  background:#155b9d;
  box-shadow: 0 0 0 2px #155b9d;
}

.twitter {
  background:rgba(255,255,255,0.1);
	bottom: 0;
	left: 25%;
}

.twitter:hover{
  background:#4099FF;
  box-shadow: 0 0 0 2px #4099FF;
}


.sociali {
  background:rgba(255,255,255,0.1);
	left: 50%;
	top: 0;
}

.sociali:hover{
  background:#f34141;
  box-shadow: 0 0 0 2px #f34141;
}

.codepen {
  background:rgba(255,255,255,0.1);
	left: 75%;
	bottom: 0;
}

.codepen:hover{
  background:#333333;
  box-shadow: 0 0 0 2px #333333;
}


.mail {
  background:rgba(255,255,255,0.1);
  left: 100%;
	top: 0;
}

.mail:hover{
  background:#1abc9c;
  box-shadow: 0 0 0 2px #1abc9c;
}

</style>

 <div class="avatar"></div>
   <h1>{{ client.Name }}</h1>
   <h1>{{ client.bio }}</h1>
   <h1>{{ client.gender }}</h1>
   <h1>{{ req.email }}</h1>
   <h1>{{ client.mobileNo }}</h1>
   <h1>Pytania: {{ client.totalQues }}</h1>
   <h1>Odpowiedzi poprawne: {{ client.totalAns }}</h1>
   <h1>Quizy:</h1>
   {% for q in quiz %}
      <h3><a href="{% url 'app:actualquiz' q.id %}">Quiz {{forloop.counter}}</a><h3>
   {% endfor %}

<div class="container">

   <ul class="social">

     <li class="facebook"><a href="{% url 'app:logout' %}">Wyloguj</a></li>
      <li class="sociali"><a href="{% url 'app:user_profiles'%}">Ranking</a></li>
     <li class="mail"><a href="{% url 'app:search' %}">Szukaj</a></li>

   </ul>

 </div>